services:
  satma.asumi.web:
    image: satma.asumi.web
    build:
      context: .
      dockerfile: Satma.Asumi.Web/Dockerfile
    environment:
      ConnectionStrings__PostgreSQL: 'Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - 5034:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
