# This is a generated file. Not intended for manual editing.
services:
  satma.asumi.web:
    build:
      context: "C:\\Users\\satma\\Desktop\\Satma.Asumi"
      dockerfile: "Satma.Asumi.Web/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Satma.Asumi.Web.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Satma.Asumi.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "satma.asumi.web:dev"
    ports: []
    volumes:
    - "C:\\Users\\satma\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\satma\\Desktop\\Satma.Asumi\\Satma.Asumi.Web:/app:rw"
    - "C:\\Users\\satma\\Desktop\\Satma.Asumi:/src:rw"
    working_dir: "/app"
